apiVersion: v1
kind: Service
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: my-react-app
  type: ClusterIP