name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'helm/**'
      - 'k8s/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reactapp-helm-argocd:${{github.run_id}}
          # platforms: linux/arm64
      
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/my-react-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "caderrimas1999@gmail.com"
          git config --global user.name "Cader Rimas"
          git add helm/my-react-app-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
